name: "Spring Boot EC2 Deploy"

inputs:
  ec2-host:
    required: true
  ec2-user:
    required: true
  ssh-key:
    required: true

runs:
  using: "composite"
  steps:

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'

    - name: Install Maven
      run: sudo apt-get update && sudo apt-get install -y maven
      shell: bash

    - name: Build JAR
      run: mvn clean package -DskipTests
      shell: bash

    - name: Prepare SSH Key
      run: |
        echo "${{ inputs.ssh-key }}" > key.pem
        chmod 400 key.pem
      shell: bash

    - name: Debug (Optional but useful)
      run: |
        ls target/
      shell: bash

    - name: Copy JAR to EC2
      run: |
        scp -o StrictHostKeyChecking=no -i key.pem $JAR_FILE ${{ inputs.ec2-user }}@${{ inputs.ec2-host }}:/home/ubuntu/app.jar
      shell: bash

    - name: Restart App on EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ${{ inputs.ec2-user }}@${{ inputs.ec2-host }} << 'EOF'
          pkill -f 'java -jar' || true
          nohup java -jar /home/ubuntu/app.jar > app.log 2>&1 &
        EOF
      shell: bash
